openagenda.settings:
  type: config_object
  label: 'OpenAgenda settings'
  mapping:
    openagenda:
      type: mapping
      mapping:
        public_key:
          type: string
          label: 'OpenAgenda account public key'
        events_per_page:
          type: int
          label: 'Number of events to show per agenda page'
        default_language:
          type: string
          label: 'Default language'
        include_embedded:
          type: boolean
          label: 'Included embedded content'
        default_map_filter_tiles_uri:
          type: string
          label: 'Default map tiles URL'
        default_map_filter_tiles_attribution:
          type: string
          label: 'Default map tiles attribution'
        default_search_filter_placeholder:
          type: label
          label: 'Default search filter placeholder'
        
        